name: Terraform Workflow

on:
  workflow_dispatch:
    inputs:
      module:
        description: "Select the Terraform module to run (e.g., ec2, vpc, rds, eks, ecr)"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - ec2
          - vpc
          - rds
          - eks
          - ecr
      action:
        description: "Select the Terraform action (plan, apply, destroy)"
        required: true
        default: "plan"
        type: choice
        options:
          - plan
          - apply
          - destroy
      environment:
        description: "Select the environment (dev, prod)"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prod

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Debug Repository Structure
      - name: List Repository Files
        run: |
          pwd
          ls -R

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      # Initialize Terraform
      - name: Terraform Init
        run: |
          terraform init -chdir=environments/${{ github.event.inputs.environment }}

      # Run Terraform Commands
      - name: Terraform ${GITHUB_EVENT_INPUTS_ACTION}
        run: |
          terraform ${GITHUB_EVENT_INPUTS_ACTION} -chdir=environments/${{ github.event.inputs.environment }} \
            -auto-approve \
            $(if [ "${{ github.event.inputs.module }}" != "all" ]; then echo "-target=module.${{ github.event.inputs.module }}"; fi)
        env:
          TF_VAR_environment: ${{ github.event.inputs.environment }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
